#!/usr/bin/zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="audio,zsh,nvim,tmux,fonts,gtk,bin"
    #STOW_FOLDERS="bin,i3,netflix,nvim,personal,tmux,uwuntu,xkb,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=~/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/clean-env
